#!/usr/bin/env bash
# Generate the shared secret, observation/skills dirs, and the per-repo
# .env files. Idempotent: existing files are left alone unless --force.
#
# What it touches (default locations; override with AOH_OBSERVATION_DIR /
# AOH_SKILLS_DIR before running):
#   $HOME/.aoh/secret           (created if missing — strong random)
#   $HOME/.aoh/observation/     (mkdir -p)
#   $HOME/.aoh/skills/          (mkdir -p)
#   $AOH_HUB_DIR/.env
#   $AOH_BRIDGE_DIR/.env
#   $AOH_OWUI_DIR/.env

. "$(dirname "$0")/lib/paths.sh"
aoh_require_repos

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

AOH_HOME="${AOH_HOME:-$HOME/.aoh}"
SECRET_FILE="$AOH_HOME/secret"
AOH_OBSERVATION_DIR="${AOH_OBSERVATION_DIR:-$AOH_HOME/observation}"
AOH_SKILLS_DIR="${AOH_SKILLS_DIR:-$AOH_HOME/skills}"

mkdir -p "$AOH_HOME" "$AOH_OBSERVATION_DIR" "$AOH_SKILLS_DIR"
aoh_ok "AOH home: $AOH_HOME"
aoh_ok "observation: $AOH_OBSERVATION_DIR"
aoh_ok "skills: $AOH_SKILLS_DIR"

# ---------- shared secret ----------
if [ ! -s "$SECRET_FILE" ]; then
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32 > "$SECRET_FILE"
  else
    "${AOH_PY:-python3.12}" -c 'import secrets; print(secrets.token_hex(32))' > "$SECRET_FILE"
  fi
  chmod 600 "$SECRET_FILE"
  aoh_ok "generated shared secret at $SECRET_FILE"
else
  aoh_dim "shared secret already exists at $SECRET_FILE (left as-is)"
fi
SHARED_SECRET="$(cat "$SECRET_FILE")"

# ---------- write_env <path> <body> ----------
write_env() {
  local target="$1"
  local body="$2"
  if [ -s "$target" ] && [ "$FORCE" -ne 1 ]; then
    aoh_dim "$target exists (rerun with --force to overwrite)"
    return
  fi
  printf '%s\n' "$body" > "$target"
  aoh_ok "wrote $target"
}

# ---------- hub .env ----------
HUB_ENV="$AOH_HUB_DIR/.env"
write_env "$HUB_ENV" "# AOH hub — generated by init-env.sh
UPSTREAM_OPENAI_BASE_URL=https://api.minimax.io/v1
UPSTREAM_OPENAI_API_KEY=REPLACE_WITH_REAL_KEY
AOH_OBSERVATION_DIR=$AOH_OBSERVATION_DIR
AOH_PAYLOAD_MODE=redacted
AOH_OBSERVATION_TAIL_ENABLED=1
"

# ---------- bridge .env ----------
BRIDGE_ENV="$AOH_BRIDGE_DIR/.env"
write_env "$BRIDGE_ENV" "# AOH bridge — generated by init-env.sh
AOH_HUB_BASE_URL=http://127.0.0.1:43180/v1
AOH_HUB_API_KEY=any
AOH_MODEL_ID=MiniMax-M2
AOH_MODEL_PROVIDER=aoh-hub
AOH_OWUI_BASE_URL=http://127.0.0.1:8080
AOH_PI_SHARED_SECRET=$SHARED_SECRET
AOH_OBSERVATION_DIR=$AOH_OBSERVATION_DIR
AOH_SKILLS_DIR=$AOH_SKILLS_DIR
AOH_PI_CLI_PATH=$AOH_PI_DIR/packages/coding-agent/dist/cli.js
AOH_PI_EXTENSION_PATH=$AOH_BRIDGE_DIR/extension/dist/owui-tools.js
AOH_BRIDGE_PORT=19000
AOH_PI_IDLE_EVICT_MS=300000
"

# ---------- owui .env ----------
OWUI_ENV="$AOH_OWUI_DIR/.env"
write_env "$OWUI_ENV" "# OWUI custom — generated by init-env.sh
AOH_PI_SHARED_SECRET=$SHARED_SECRET
OPENAI_API_BASE_URLS=http://127.0.0.1:19000/v1
OPENAI_API_KEYS=ignored
MINIMAX_BASE_URL=https://api.minimax.io/v1
MINIMAX_API_KEY=REPLACE_WITH_REAL_KEY
MINIMAX_MODEL=MiniMax-M2
"

echo
aoh_ok "Environment files ready. Next step:"
aoh_dim "  1. fill in UPSTREAM_OPENAI_API_KEY / MINIMAX_API_KEY in the .env files above"
aoh_dim "  2. initialise hub DB:   (cd $AOH_HUB_DIR && scripts/init_db.sh)"
aoh_dim "  3. run smoke test:      scripts/aoh/smoke-test.sh"
